### ISSUE TITLE
Issue with Angular2 beta 

### ISSUE THREAD

**Issue by gstrit** [jhades/angular2-redux-store#6]
Hello,

It seems that your example doesn't work with beta.X version of angular.
The application is launching correctly but I am not able to add a new todo. The list is not updated.

**Comment by alexanderharm** [comment]
Probably due to all kind of dependencies missing, first of all the now required polyfills. I guess you have to update `index.html` with the necessary dependencies: `angular2-polyfills.js` and `rxjs`.

**Comment by jhades** [comment]
Thanks for the issue report, I've upgraded the example to beta-3 and angular2-redux-store 1.2.0

**Comment by gstrit** [comment]
You're welcome !
